version: '3.3'

services:
  app:
    image: virvira/hw26:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - 8080:25000
    depends_on:
      - db
    environment:
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_USER=$DB_USER
      - POSTGRES_DB=$DB_NAME
