version: '3.3'

services:
  app:
    build: .
    ports:
      - 8080:25000
    depends_on:
      - db
    environment:
      - DB_NAME=name_test
      - DB_USER=user_test
      - DB_PASSWORD=pass_test
      - DB_HOST=db
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=pass_test
      - POSTGRES_USER=user_test
      - POSTGRES_DB=name_test